#!/bin/bash

# Version de l'application
VERSION="4.1.3"

############################################################################ 
### DEBUT: NE PAS MODIFIER CETTE SECTION
############################################################################ 

exec &>> "/tmp/suppression-R.outpout.`date +%Y-%m-%d-%s`"
umask 0022

PATH_TO_INSTALL="${1}/R-${VERSION}"     # Repertoire d'installation
MODULEFILES_DIR="${2}" 
#LOCAL_ARTEFACT="${2}"                   # Depot UdeM des sources externes;

############################################################################ 
### FIN: NE PAS MODIFIER CETTE SECTION
############################################################################ 


#[[ -e "${LOCAL_ARTEFACT}/R-${VERSION}.tar.gz" ]] && {
#    echo "# SENS ############ Supression de l'artefact ${LOCAL_ARTEFACT}/R-${VERSION}.tar.gz";
#    rm "${LOCAL_ARTEFACT}/R-${VERSION}.tar.gz";
#}

[[ -e "${PATH_TO_INSTALL}" ]] && {
    echo "# SENS ############ Supression de l'application ${PATH_TO_INSTALL}/R-${VERSION}";
    rm -rf ${PATH_TO_INSTALL}/R-${VERSION};
}

[[ -e "${MODULEFILES_DIR}/r-4.1.3.lua" ]] && {
    echo "# SENS ############ Supression du modulefiles ${MODULEFILES_DIR}/r-4.1.3.lua";
    rm ${MODULEFILES_DIR}/r-4.1.3.lua;
}

############################################################################ 
### DEBUT: NE PAS MODIFIER CETTE SECTION
############################################################################ 

############################################################################ 
### FIN: NE PAS MODIFIER CETTE SECTION
############################################################################ 